name: Update ASN China List

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点运行一次
  push:
    branches:
      - main  # 当推送到main分支时运行
  workflow_dispatch:  # 手动触发

jobs:
  update_asn_list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run Python scripts
        run: python py/asn-cn-scraper.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update asn.cn.names.list and asn-cn.list"
          file_pattern: |
            asn.cn.names.list
            asn.cn.list
